//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pass {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pass.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        public static string allow {
            get {
                return ResourceManager.GetString("allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing :.
        /// </summary>
        public static string allowSharing {
            get {
                return ResourceManager.GetString("allowSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  would like to share .
        /// </summary>
        public static string appv1 {
            get {
                return ResourceManager.GetString("appv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string appv2 {
            get {
                return ResourceManager.GetString("appv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask before share : .
        /// </summary>
        public static string AskBeforeShare {
            get {
                return ResourceManager.GetString("AskBeforeShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You would like to share .
        /// </summary>
        public static string askBeforeShare1 {
            get {
                return ResourceManager.GetString("askBeforeShare1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        ///Are you sure?.
        /// </summary>
        public static string askBeforeShare2 {
            get {
                return ResourceManager.GetString("askBeforeShare2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically scan when Pass is launched : .
        /// </summary>
        public static string AutoScanOnLaunch {
            get {
                return ResourceManager.GetString("AutoScanOnLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically scan when Pass is showing : .
        /// </summary>
        public static string AutoScanOnVisible {
            get {
                return ResourceManager.GetString("AutoScanOnVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Startup : .
        /// </summary>
        public static string AutoStartOnComputerBoot {
            get {
                return ResourceManager.GetString("AutoStartOnComputerBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Path.
        /// </summary>
        public static string DefaultSavingPath {
            get {
                return ResourceManager.GetString("DefaultSavingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Path :.
        /// </summary>
        public static string DefaultSavingPathSetter {
            get {
                return ResourceManager.GetString("DefaultSavingPathSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied.
        /// </summary>
        public static string denied {
            get {
                return ResourceManager.GetString("denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        public static string deny {
            get {
                return ResourceManager.GetString("deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow me to be discovered by:.
        /// </summary>
        public static string discovered {
            get {
                return ResourceManager.GetString("discovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t see who you&apos;re looking for?.
        /// </summary>
        public static string doesntappear {
            get {
                return ResourceManager.GetString("doesntappear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peer has a problem with a file.
        /// </summary>
        public static string FileErr {
            get {
                return ResourceManager.GetString("FileErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find file to be shared.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding people to share.
        /// </summary>
        public static string finding {
            get {
                return ResourceManager.GetString("finding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied.
        /// </summary>
        public static string hate {
            get {
                return ResourceManager.GetString("hate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peer did abnormal respons.
        /// </summary>
        public static string invalid {
            get {
                return ResourceManager.GetString("invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address: .
        /// </summary>
        public static string ip_addr {
            get {
                return ResourceManager.GetString("ip_addr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string ipAddr {
            get {
                return ResourceManager.GetString("ipAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string LANG_CODE {
            get {
                return ResourceManager.GetString("LANG_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language :.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string love {
            get {
                return ResourceManager.GetString("love", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC Address.
        /// </summary>
        public static string MacAddress {
            get {
                return ResourceManager.GetString("MacAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name :.
        /// </summary>
        public static string myName {
            get {
                return ResourceManager.GetString("myName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your PC.
        /// </summary>
        public static string mypc {
            get {
                return ResourceManager.GetString("mypc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string network {
            get {
                return ResourceManager.GetString("network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No one to share with....
        /// </summary>
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why no one shown in the list?.
        /// </summary>
        public static string noneVisible {
            get {
                return ResourceManager.GetString("noneVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sharing file selected.
        /// </summary>
        public static string nosel {
            get {
                return ResourceManager.GetString("nosel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable sharing option to share file.
        /// </summary>
        public static string notSharing {
            get {
                return ResourceManager.GetString("notSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Pass.
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open load page on start :.
        /// </summary>
        public static string OpenLogPageAlways {
            get {
                return ResourceManager.GetString("OpenLogPageAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass Protocol Version.
        /// </summary>
        public static string PassProtocolVersion {
            get {
                return ResourceManager.GetString("PassProtocolVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass Version.
        /// </summary>
        public static string PassVersion {
            get {
                return ResourceManager.GetString("PassVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As scan time is long you may find device with slow device, but you have to wait longer time.
        ///Normaly, shorter than a second is also good..
        /// </summary>
        public static string pingTimeExplain {
            get {
                return ResourceManager.GetString("pingTimeExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Scan Timeout(ms) :.
        /// </summary>
        public static string PingTimeout {
            get {
                return ResourceManager.GetString("PingTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still having problem?.
        /// </summary>
        public static string problem {
            get {
                return ResourceManager.GetString("problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered IP only.
        /// </summary>
        public static string regedonly {
            get {
                return ResourceManager.GetString("regedonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping Replies.
        /// </summary>
        public static string responeAsHost {
            get {
                return ResourceManager.GetString("responeAsHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string response {
            get {
                return ResourceManager.GetString("response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping from local(Denied).
        /// </summary>
        public static string self {
            get {
                return ResourceManager.GetString("self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending.
        /// </summary>
        public static string sending {
            get {
                return ResourceManager.GetString("sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string sent {
            get {
                return ResourceManager.GetString("sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share With Pass.
        /// </summary>
        public static string shareWith {
            get {
                return ResourceManager.GetString("shareWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must turn sharing on to share.
        /// </summary>
        public static string sharingAlert {
            get {
                return ResourceManager.GetString("sharingAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why no one here?.
        /// </summary>
        public static string sup {
            get {
                return ResourceManager.GetString("sup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Mismatch(Denied).
        /// </summary>
        public static string vers {
            get {
                return ResourceManager.GetString("vers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot share with different version of Pass.
        /// </summary>
        public static string versMismatch {
            get {
                return ResourceManager.GetString("versMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn what to do.
        /// </summary>
        public static string viewSup {
            get {
                return ResourceManager.GetString("viewSup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show statusbar on start :.
        /// </summary>
        public static string VisibleStatusBarOnLaunch {
            get {
                return ResourceManager.GetString("VisibleStatusBarOnLaunch", resourceCulture);
            }
        }
    }
}
