//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pass {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pass.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    would like to share 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string appv1 {
            get {
                return ResourceManager.GetString("appv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string appv2 {
            get {
                return ResourceManager.GetString("appv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allow me to be discovered by:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string discovered {
            get {
                return ResourceManager.GetString("discovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t see who you&apos;re looking for?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string doesntappear {
            get {
                return ResourceManager.GetString("doesntappear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Peer has a problem with a file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FileErr {
            get {
                return ResourceManager.GetString("FileErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot find file to be shared과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finding people to share과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string finding {
            get {
                return ResourceManager.GetString("finding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Peer did abnormal respons과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string invalid {
            get {
                return ResourceManager.GetString("invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP Address: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ip_addr {
            get {
                return ResourceManager.GetString("ip_addr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your PC과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string mypc {
            get {
                return ResourceManager.GetString("mypc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No one to share with...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No sharing file selected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string nosel {
            get {
                return ResourceManager.GetString("nosel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable sharing option to share file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string notSharing {
            get {
                return ResourceManager.GetString("notSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Still having problem?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string problem {
            get {
                return ResourceManager.GetString("problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registered IP only과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string regedonly {
            get {
                return ResourceManager.GetString("regedonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Why no one here?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sup {
            get {
                return ResourceManager.GetString("sup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pass과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Learn what to do과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string viewSup {
            get {
                return ResourceManager.GetString("viewSup", resourceCulture);
            }
        }
    }
}
